//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFDataSample
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SIGACEntities : DbContext
    {
        public SIGACEntities()
            : base("name=SIGACEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Empresas> Empresas { get; set; }
        public virtual DbSet<Empresas_Admon> Empresas_Admon { get; set; }
        public virtual DbSet<Empresas_Admon_Cargos> Empresas_Admon_Cargos { get; set; }
        public virtual DbSet<Empresas_Sucursales> Empresas_Sucursales { get; set; }
        public virtual DbSet<Empresas_Tipos> Empresas_Tipos { get; set; }
        public virtual DbSet<Personas> Personas { get; set; }
        public virtual DbSet<Util_Ciudades> Util_Ciudades { get; set; }
        public virtual DbSet<Util_Dptos> Util_Dptos { get; set; }
        public virtual DbSet<Util_Paises> Util_Paises { get; set; }
    }
}
