//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFDataSample
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresas_Admon
    {
        public int EmpresaId { get; set; }
        public int CargoId { get; set; }
        public int PersonaId { get; set; }
        public string Matricula { get; set; }
        public Nullable<System.DateTime> Creado { get; set; }
        public Nullable<bool> Activo { get; set; }
        public byte[] Modified { get; set; }
        public string Usuario { get; set; }
    
        public virtual Empresas Empresas { get; set; }
        public virtual Empresas_Admon_Cargos Empresas_Admon_Cargos { get; set; }
        public virtual Personas Personas { get; set; }
    }
}
