//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFDataSample
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresas_Admon_Cargos
    {
        public Empresas_Admon_Cargos()
        {
            this.Empresas_Admon = new HashSet<Empresas_Admon>();
        }
    
        public int CargoId { get; set; }
        public string NombreCargo { get; set; }
        public Nullable<System.DateTime> Creado { get; set; }
        public Nullable<bool> Activo { get; set; }
        public byte[] Modified { get; set; }
        public string Usuario { get; set; }
    
        public virtual ICollection<Empresas_Admon> Empresas_Admon { get; set; }
    }
}
