//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFDataSample
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresas_Sucursales
    {
        public int EmpresaId { get; set; }
        public int SucursalId { get; set; }
        public int PaisId { get; set; }
        public int DptoId { get; set; }
        public int CiudadId { get; set; }
        public Nullable<System.DateTime> Creado { get; set; }
        public Nullable<bool> Activo { get; set; }
        public byte[] Modified { get; set; }
        public string Usuario { get; set; }
    
        public virtual Empresas Empresas { get; set; }
        public virtual Util_Ciudades Util_Ciudades { get; set; }
        public virtual Util_Dptos Util_Dptos { get; set; }
        public virtual Util_Paises Util_Paises { get; set; }
    }
}
