//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFDataSample
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresas
    {
        public Empresas()
        {
            this.Empresas_Admon = new HashSet<Empresas_Admon>();
            this.Empresas_Sucursales = new HashSet<Empresas_Sucursales>();
        }
    
        public int EmpresaId { get; set; }
        public string Nit { get; set; }
        public string NombreCorto { get; set; }
        public string NombreLargo { get; set; }
        public Nullable<bool> TieneSucursales { get; set; }
        public Nullable<int> TipoEmpresaId { get; set; }
        public Nullable<int> PaisId { get; set; }
        public Nullable<int> DptoId { get; set; }
        public Nullable<int> CiudadId { get; set; }
        public Nullable<System.DateTime> Fundada { get; set; }
        public string FundadeEn { get; set; }
        public string DocumentoLegal { get; set; }
        public Nullable<bool> GranContribuyente { get; set; }
        public Nullable<bool> Principal { get; set; }
        public Nullable<System.DateTime> Creado { get; set; }
        public bool Activo { get; set; }
        public byte[] Modified { get; set; }
        public string Usuario { get; set; }
    
        public virtual ICollection<Empresas_Admon> Empresas_Admon { get; set; }
        public virtual Empresas_Tipos Empresas_Tipos { get; set; }
        public virtual ICollection<Empresas_Sucursales> Empresas_Sucursales { get; set; }
        public virtual Util_Ciudades Util_Ciudades { get; set; }
        public virtual Util_Dptos Util_Dptos { get; set; }
        public virtual Util_Paises Util_Paises { get; set; }
    }
}
