//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFDataSample
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresas_Tipos
    {
        public Empresas_Tipos()
        {
            this.Empresas = new HashSet<Empresas>();
        }
    
        public int TipoEmpresaId { get; set; }
        public string NombreTipo { get; set; }
        public Nullable<System.DateTime> Creado { get; set; }
        public Nullable<bool> Activo { get; set; }
        public byte[] Modified { get; set; }
        public string Usuario { get; set; }
    
        public virtual ICollection<Empresas> Empresas { get; set; }
    }
}
