//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFDataSample
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personas
    {
        public Personas()
        {
            this.Empresas_Admon = new HashSet<Empresas_Admon>();
        }
    
        public int PersonaId { get; set; }
        public string Nit { get; set; }
        public bool Juridico { get; set; }
        public string Digito { get; set; }
        public string RazonSocial { get; set; }
        public string Nombre { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public int PaisId { get; set; }
        public int DptoId { get; set; }
        public int CiudadId { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public Nullable<System.DateTime> Creado { get; set; }
        public Nullable<bool> Activo { get; set; }
        public byte[] Modified { get; set; }
        public string Usuario { get; set; }
    
        public virtual ICollection<Empresas_Admon> Empresas_Admon { get; set; }
        public virtual Util_Ciudades Util_Ciudades { get; set; }
        public virtual Util_Dptos Util_Dptos { get; set; }
        public virtual Util_Paises Util_Paises { get; set; }
    }
}
