//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFDataSample
{
    using System;
    using System.Collections.Generic;
    
    public partial class Util_Paises
    {
        public Util_Paises()
        {
            this.Empresas = new HashSet<Empresas>();
            this.Empresas_Sucursales = new HashSet<Empresas_Sucursales>();
            this.Personas = new HashSet<Personas>();
            this.Util_Dptos = new HashSet<Util_Dptos>();
        }
    
        public int PaisId { get; set; }
        public string NombrePais { get; set; }
        public string ISO2 { get; set; }
        public string ISO3 { get; set; }
        public string Web { get; set; }
        public string UN { get; set; }
        public string Phone { get; set; }
        public byte[] Modified { get; set; }
    
        public virtual ICollection<Empresas> Empresas { get; set; }
        public virtual ICollection<Empresas_Sucursales> Empresas_Sucursales { get; set; }
        public virtual ICollection<Personas> Personas { get; set; }
        public virtual ICollection<Util_Dptos> Util_Dptos { get; set; }
    }
}
