//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFDataSample
{
    using System;
    using System.Collections.Generic;
    
    public partial class Util_Ciudades
    {
        public Util_Ciudades()
        {
            this.Empresas = new HashSet<Empresas>();
            this.Empresas_Sucursales = new HashSet<Empresas_Sucursales>();
            this.Personas = new HashSet<Personas>();
        }
    
        public int PaisId { get; set; }
        public int DptoId { get; set; }
        public int CiudadId { get; set; }
        public string NombreCiudad { get; set; }
        public Nullable<bool> Capital { get; set; }
        public System.Data.Entity.Spatial.DbGeography GPSUbicacion { get; set; }
        public byte[] Modified { get; set; }
    
        public virtual ICollection<Empresas> Empresas { get; set; }
        public virtual ICollection<Empresas_Sucursales> Empresas_Sucursales { get; set; }
        public virtual ICollection<Personas> Personas { get; set; }
        public virtual Util_Dptos Util_Dptos { get; set; }
    }
}
