//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFDataSample
{
    using System;
    using System.Collections.Generic;
    
    public partial class Util_Dptos
    {
        public Util_Dptos()
        {
            this.Empresas = new HashSet<Empresas>();
            this.Empresas_Sucursales = new HashSet<Empresas_Sucursales>();
            this.Personas = new HashSet<Personas>();
            this.Util_Ciudades = new HashSet<Util_Ciudades>();
        }
    
        public int PaisId { get; set; }
        public int DptoId { get; set; }
        public string DptoNombre { get; set; }
        public byte[] Modified { get; set; }
    
        public virtual ICollection<Empresas> Empresas { get; set; }
        public virtual ICollection<Empresas_Sucursales> Empresas_Sucursales { get; set; }
        public virtual ICollection<Personas> Personas { get; set; }
        public virtual ICollection<Util_Ciudades> Util_Ciudades { get; set; }
        public virtual Util_Paises Util_Paises { get; set; }
    }
}
